spring:
  application:
    name: notificationservice
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: admin
    password: password123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: indu
      password: indu

  # REDISSON CONFIGURATION
  # This replaces the 'data: redis:' block
  redisson:
    config: |
      singleServerConfig:
        address: "redis://${REDIS_HOST:localhost}:6379"
        connectionMinimumIdleSize: 10
        connectionPoolSize: 64


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group-v3
      auto-offset-reset: earliest
      # Since we are using ObjectMapper in the consumer code,
      # we can just use StringDeserializer directly.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  autoconfigure:
    # This stops Spring Boot from looking for the Redis classes that are crashing your app
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

server:
  port: 8083
